export { default as CRMKanban } from './CRMKanban'
export { default as CRMDashboard } from './CRMDashboard'
export { default as CRMDashboardComAbas } from './CRMDashboardComAbas'
export { default as CRMFunilCX } from './CRMFunilCX'
export { default as CRMComAbas } from './CRMComAbas'
